/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Hub */

#ifndef _Included_jni_Hub
#define _Included_jni_Hub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Hub
 * Method:    initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jni_Hub_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jni_Hub
 * Method:    waitForMyo
 * Signature: (J)Ljni/Myo;
 */
JNIEXPORT jobject JNICALL Java_jni_Hub_waitForMyo
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
