/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myojni_jni_DeviceListener */

#ifndef _Included_myojni_jni_DeviceListener
#define _Included_myojni_jni_DeviceListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myojni_jni_DeviceListener
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myojni_jni_DeviceListener_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
