/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myojni_jni_Myo */

#ifndef _Included_myojni_jni_Myo
#define _Included_myojni_jni_Myo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myojni_jni_Myo
 * Method:    vibrate
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_myojni_jni_Myo_vibrate
  (JNIEnv *, jobject, jint);

/*
 * Class:     myojni_jni_Myo
 * Method:    requestRssi
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myojni_jni_Myo_requestRssi
  (JNIEnv *, jobject);

/*
 * Class:     myojni_jni_Myo
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myojni_jni_Myo_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
