/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class myojni_jni_Vector3 */

#ifndef _Included_myojni_jni_Vector3
#define _Included_myojni_jni_Vector3
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
